### ISSUE TITLE
there is no end of string check

### ISSUE THREAD

**Issue by hamza-cskn** [emreakdik/minishell#5]
https://github.com/emreakdik/minishell/blob/f61e47a3b79d123bb9a3ad50f1ce6321c6eae561/src/lexer/lexer.c#L22C9-L22C25

**Comment by hamza-cskn** [comment]
my bad: https://github.com/emreakdik/minishell/blob/f61e47a3b79d123bb9a3ad50f1ce6321c6eae561/src/main/main.c#L102

**Comment by Bero000** [comment]
thats ok
