### ISSUE TITLE
"ls -la >> ~/Desktop/asd.txt" gibi mutlak konumlu dosya açma hataların çözümü

### ISSUE THREAD

**Issue by marasama** [emreakdik/minishell#8]
# Yönlerdirme operatörleri hatalı çalışıyor çünkü;

create_files.c dosyasındaki create_out_files_me fonksiyonunda yeni dosya açarken sadece göreceli konumu kullanılabiliyor
Mutlak konumu girildiğinde dosya açılmıyor ve yönlendirme operatörü çalışmadan direkt çıktı veriyor.

`       getcwd(str, 256);`
`	m_next = current_parse->next;`
`	temp = ft_strjoin(str, "/");`
`	pwd = ft_strjoin(temp, m_next->text[0]);`
`	free(temp);`

Dosya açarken güncel konumun üzerine mutlak konumu eklediği için dosya açılamıyor
Çözüme cdhir hazır fonksiyonunu kullanarak ulaşabileceğimizi düşünüyorum.
Yorgun olduğum için bugün ilgilenemem ama en kısa sürede halledebilirim.
chdir göreceli konumu ve mutlak konumu ele alan bir fonksiyon. chdir ile verilen konuma gidip, dosyayı açıp sonrasında $OLDPWD ile geri dönersek ve $OLDPWD'yi de hiç kullanılmamış gibi değiştirirsek hallederiz gibi duruyor.

**Comment by emreakdik** [comment]
create_out_files_me fonksiyonunda get_env fonksiyonu ile HOME degikseninin karsiligi alinip text'in HOME degiskeninin karsiligiyla baslayip baslamadigi strnstr fonksiyonuyla kontrol edilebilir eger bu sekilde basliyorsa mutlak yoldur ve diger islemler yapilmaz, sonuna sadece text eklenebilir. open komutu dosyayi acmak icin kendiliginden verilen mutlak yolu goruyor ve orada konum aciyor zaten. Asagida ornek bir kod yazdim. Bu kod sana onerdigim cozum icin bir yol haritasi da verecektir
 ```c
 #include <fcntl.h>
#include <stdio.h> 
#include <string.h>
#include <unistd.h>

int	main(void)
{
   char *path = "/Users/emre/Desktop/a.txt";

   int fd = open(path, O_CREAT | O_RDWR, 0777);
   if (fd == -1)
   {
      perror("open"); 
      return (1);       
   }

   char *str = "Hello World!";
   int bytes_written = write(fd, str, strlen(str));
   if (bytes_written == -1)
   {
      perror("write"); 
      close(fd);       
      return (1);
   }
   close(fd);
   return (0);
}
```
